# Generated by Django 6.0.6 on 2026-07-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0006_order_remove_cart_created_at_cart_session_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='nom',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tel',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='produits',
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.TextField(default=1, help_text='Products grouped by brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('client', 'Client')], max_length=20),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('furniture', 'Furniture'), ('lighting', 'Lighting'), ('materials', 'Materials'), ('wellness', 'Wellness')], max_length=50, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_cover', models.ImageField(blank=True, null=True, upload_to='products/covers/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='immobilier.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='immobilier.product')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='immobilier.product'),
            preserve_default=False,
        ),
    ]
