# Generated by Django 6.0.6 on 2026-07-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0008_cartitem_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='ImageProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
