# Generated by Django 6.0.6 on 2026-07-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0009_remove_product_brand_remove_imageproduct_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pdf_file',
            new_name='pdf',
        ),
    ]
