# Generated by Django 6.0.6 on 2026-07-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0011_alter_order_options_remove_order_order_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
